---
- name: Provisioning webservers 
  hosts: webservers
  become: yes
  vars:
    user: root
    group: docker
    traefik_dir: /var/www/traefik
  tasks:
    - include: tasks/ufw.yml
  handlers:
    - include: handlers/ufw.yml
  roles:
    - { role: docker, tags: docker }
    - { role: traefik, tags: traefik }
    - { role: sonarqube, tags: sonarqube }
